### ISSUE TITLE
How does this differ from NeutrinosPlatform's plugin of the same name?

### ISSUE THREAD

**Issue by mLuby** [Skydragonsz/cordova-plugin-document-scanner#8]
https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner

**Comment by Skydragonsz** [comment]
1. This was the project that I had to make for my internship! 
2. This repo is not really maintained and neither is in any store/plugin directory. 
3. Neutrinos docscanner supports Android, mine doesn't. 
4. Not sure about this one but mine can save to photo album if needed. 
5. You can change the options in mine, Neutrinos only allowed you to change sourceType
